/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package useGradleAndMaps;
import com.google.maps.errors.ApiException;

import java.io.IOException;

import org.json.*;

public class UseMaps {
    public static void main(String[] args) throws ApiException, InterruptedException, JSONException, IOException {
        new Gui();   
    }
}
